name: Shell Format Check

on:
  pull_request:

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run sh-checker
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 0 -d
        with:
          sh_checker_comment: true
          sh_checker_only_diff: true
          sh_checker_shellcheck_disable: true
